FROM debian:experimental

RUN apt update && apt install -y make build-essential git libpam0g-dev sudo pamtester gdb
RUN apt update && apt install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf gcc-hppa64-linux-gnu gcc-i686-linux-gnu gcc-powerpc64le-linux-gnu gcc-s390x-linux-gnu gcc-mips-linux-gnu gcc-mipsel-linux-gnu gcc-alpha-linux-gnu gcc-arc-linux-gnu gcc-hppa-linux-gnu gcc-m68k-linux-gnu gcc-powerpc-linux-gnu gcc-powerpc64-linux-gnu gcc-riscv64-linux-gnu gcc-sh4-linux-gnu gcc-sparc64-linux-gnu
