on:
    push:
        tags:
            - '*.*.*'
    workflow_dispatch:

jobs:
    create_release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Create Release
              uses: ncipollo/release-action@v1
    build:
        runs-on: ubuntu-latest
        needs: create_release
        permissions:
            contents: write
        strategy:
            fail-fast: false
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install packages
              run: |
                sudo apt update
                sudo apt install -y make build-essential libpam0g-dev
            - name: Set Environment Variables
              run: |
                echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
                echo "ARCH=arm64" >> $GITHUB_ENV
            - name: Build
              run: make package
            - name: Upload Release Asset
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: package/libpam-daily-word_${{ github.ref_name }}_arm64.deb
                asset_name: libpam-daily-word_${{ github.ref_name }}_arm64.deb
                overwrite: false
            - name: Upload Release Artifact
              uses: actions/upload-artifact@v4
              with:
                name: libpam-daily-word_${{ github.ref_name }}_arm64.deb
                path: package/libpam-daily-word_${{ github.ref_name }}_arm64.deb
    repository:
        runs-on: ubuntu-latest
        needs: build
        container:
            image: debian:experimental
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Download Release Artifact
              uses: actions/download-artifact@v4
              with:
                name: libpam-daily-word_${{ github.ref_name }}_arm64.deb
                path: /tmp
            - name: Install Packages
              env:
                GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
                GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
              run: |
                apt update
                apt install -t experimental reprepro -y
                echo "$GPG_PRIVATE_KEY" | tr '|' '\n' | gpg --batch --yes --import --verbose
                gpg --verbose --pinentry-mode loopback -su 'manindark@own.manindark.me' --batch --passphrase "$GPG_PASSPHRASE" list
                reprepro -b repository/debian includedeb bookworm /tmp/libpam-daily-word_${{ github.ref_name }}_amd64.deb
                git add repository/debian
                git config --global user.name "repository maintainer bot"
                git config --global user.email "manindark@users.noreply.com"
                git commit -m "apt repository update"
                git push
