on:
    push:
        tags:
            - '*.*.*'
    workflow_dispatch:

jobs:
    create_release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Create Release
              uses: ncipollo/release-action@v1
    build:
        runs-on: ubuntu-latest
        needs: create_release
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                platform: [amd64, arm64, armhf]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install packages
              run: |
                sudo apt update
                sudo apt install -y make build-essential libpam0g-dev
            - name: Set Environment Variables
              run: |
                echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
                echo "ARCH=${{ matrix.platform }}" >> $GITHUB_ENV
            - name: Build
              run: make package
            - name: Upload Release Asset
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: package/libpam-daily-word_${{ github.ref_name }}_${{ matrix.platform }}.deb
                asset_name: libpam-daily-word_${{ github.ref_name }}_${{ matrix.platform }}.deb
                overwrite: false