on:
    push:
        branches:
            - main
        paths:
            - "provider.c"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install packages
              run: |
                  sudo apt update
                  sudo apt install -y make build-essential libpam0g-dev
            - name: Build
              run: make build
