on: 
    push: 
        branches: 
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                platform:
                    - linux/amd64
                    - linux/arm64
                    - linux/arm/v7
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install packages
              run: |
                  sudo apt update
                  sudo apt install -y make build-essential libpam0g-dev
            - name: Build
              run: make build